import { useEffect, useState } from 'react';
import { signInWithEmailAndPassword, onAuthStateChanged, signOut, User } from 'firebase/auth';
import { collection, onSnapshot, query } from 'firebase/firestore';
import { Activity, Archive, ChevronRight, FileText, KeyRound, LayoutDashboard, LogOut, Menu, ShieldCheck, UserRound, Users, X } from 'lucide-react';
import { auth, db, firebaseConfigured } from './firebase';

type Section = 'Dashboard' | 'Digital Assets' | 'Document Vault' | 'Executors' | 'Instructions';
const nav: { label: Section; icon: typeof LayoutDashboard }[] = [{ label: 'Dashboard', icon: LayoutDashboard }, { label: 'Digital Assets', icon: KeyRound }, { label: 'Document Vault', icon: FileText }, { label: 'Executors', icon: Users }, { label: 'Instructions', icon: Archive }];

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [section, setSection] = useState<Section>('Dashboard'); const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [counts, setCounts] = useState([0, 0, 0, 0]);
  useEffect(() => auth ? onAuthStateChanged(auth, setUser) : undefined, []);
  useEffect(() => { if (!db || !user) return; const names = ['assets', 'documents', 'executors', 'instructions']; const unsubs = names.map((name, index) => onSnapshot(query(collection(db, 'users', user.uid, name)), snap => setCounts(previous => previous.map((count, i) => i === index ? snap.size : count)))); return () => unsubs.forEach(unsubscribe => unsubscribe()); }, [user]);
  if (!user) return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} />;
  const admin = user.email === 'admin@legacy.com';
  return <div className={`app ${admin ? 'admin-app' : ''}`}><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-icon"><ShieldCheck size={18} /></span><span>Legacy Vault<small>SYSTEM</small></span><button className="close-menu" onClick={() => setOpen(false)}><X size={18} /></button></div><nav><span className="nav-heading">MAIN MENU</span>{nav.map(({ label, icon: Icon }) => <button className={section === label ? 'nav-item active' : 'nav-item'} onClick={() => { setSection(label); setOpen(false); }} key={label}><Icon size={17} /><span>{label}</span></button>)}<span className="nav-heading account">ACCOUNT</span><button className="nav-item"><UserRound size={17} /><span>Profile</span></button></nav><button className="sign-out" onClick={() => auth && signOut(auth)}><LogOut size={17} />Sign Out</button></aside><main><header><button className="mobile-trigger" onClick={() => setOpen(true)}><Menu size={20} /></button><span className="mobile-brand">Legacy Vault</span><span className="secure"><span />SECURE WORKSPACE</span></header>{admin ? <Admin /> : <Dashboard user={user} counts={counts} section={section} />}</main></div>;
}
function Login({ email, password, setEmail, setPassword }: { email: string; password: string; setEmail: (value: string) => void; setPassword: (value: string) => void }) { const [error, setError] = useState(''); return <div className="login"><div className="login-card"><div className="brand login-brand"><span className="brand-icon"><ShieldCheck size={18} /></span><span>Legacy Vault<small>SYSTEM</small></span></div><span className="eyebrow">SECURE ACCESS</span><h1>Welcome back</h1><p>Manage and secure your digital legacy.</p>{!firebaseConfigured && <div className="notice">Add Firebase values to <b>.env.local</b> to enable authentication.</div>}<form onSubmit={async event => { event.preventDefault(); if (!auth) return; try { await signInWithEmailAndPassword(auth, email, password); } catch { setError('Unable to sign in with those details.'); } }}><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label>{error && <small className="error">{error}</small>}<button className="primary">Sign In <ChevronRight size={16} /></button></form></div></div> }
function Dashboard({ user, counts, section }: { user: User; counts: number[]; section: Section }) { if (section !== 'Dashboard') return <div className="placeholder"><span className="eyebrow">WORKSPACE</span><h1>{section}</h1><p>This section is ready for your Firebase data.</p></div>; const cards = [{ title: 'Digital Assets', value: counts[0], desc: 'Accounts and services', icon: KeyRound }, { title: 'Documents', value: counts[1], desc: 'Protected files', icon: FileText }, { title: 'Executors', value: counts[2], desc: 'Trusted contacts', icon: Users }, { title: 'Instructions', value: counts[3], desc: 'Guidance for later', icon: Archive }]; const health = counts.filter(Boolean).length * 25; return <div className="content"><div className="heading"><div><span className="eyebrow">YOUR LEGACY, SECURED</span><h1>Welcome Back, {user.displayName || user.email?.split('@')[0]}!</h1><p>Manage and secure your digital legacy</p></div><button className="primary">+ Add Digital Asset</button></div><div className="stats">{cards.map(({ title, value, desc, icon: Icon }) => <div className="stat" key={title}><Icon className="gold-icon" size={20} /><span>{title}</span><strong>{value}</strong><small>{desc}</small></div>)}</div><div className="lower"><section className="panel"><div className="panel-title"><div><span className="eyebrow">VAULT HEALTH</span><h2>Your vault is {health}% ready</h2></div><strong className="health">{health}%</strong></div><div className="progress"><i style={{ width: `${health}%` }} /></div><p>Complete each part of your vault to make your wishes clear and actionable.</p>{cards.map(card => <div className="check" key={card.title}><span className={card.value ? 'complete' : ''}>✓</span>{card.title}<small>{card.value ? 'Complete' : 'Not started'}</small></div>)}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">TIMELINE</span><h2>Recent Activity</h2></div><Activity size={18} /></div><div className="empty"><Activity size={25} /><p>Your vault activity will appear here.</p></div></section></div></div> }
function Admin() { return <div className="content"><div className="heading"><div><span className="eyebrow">ADMIN CONSOLE</span><h1>System overview</h1><p>Monitor verification and platform activity.</p></div></div><div className="admin-banner"><ShieldCheck size={28} /><div><b>Administrator access</b><span>Review system activity and verification requests.</span></div></div><div className="stats"><div className="stat"><Users className="gold-icon" size={20} /><span>Total Users</span><strong>--</strong><small>Firestore connection required</small></div><div className="stat"><Activity className="gold-icon" size={20} /><span>Pending Reviews</span><strong>--</strong><small>Verification queue</small></div></div></div> }
